version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(message)s" #Log format
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    format: '{"time": "%(asctime)s", "name": "%(name)s", "level": "%(levelname)s", "fileName": %(filename)s,"message": "%(message)s"}'
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: info.log #path can be included
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: error.log #path can be included
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  root: # This is a default setting for loggers. you can use consle and file handler as default handlers.
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: no
